

AUTHORIZATION = "Authorization"
CURRENT_BAL = 'currentBalance'
CURRENCY = 'currency'
BALANCE = 'balance'
CREDIT= 'CREDIT'
DEBIT='DEBIT'
HASH_KEY = 'hash_key'
PASSWORD = 'password'
USERNAME = 'mobileno'
RECIPIENT = 'recipient'
WALLET_USER = 'user'
MODEL_WALLET_USER = 'WalletUser'
EMAIL = 'email_id'
NAME='name'
USER_IS_NOT_ACTIVE = 'USER_IS_NOT_ACTIVE'
AMOUNT = 'amount'
user_hash = 'user_hash'
TRANSACTION_TYPE = 'transaction_type'
TRANSACTION_STATUS = 'transaction_status'
REASON = 'reason'
INPROGRESS= 'IN_PROGRESS'
SUCCESS='SUCCESS'
FAILED= 'FAILED'
NOT_VALID_DATE_RANGE ='NOT_VALID_DATE_RANGE'
COMPLETED = 'COMPLETED'
TRANSACTION_DATE = 'transaction_date'
SENDER = 'sender'
STARTDATE = 'startdate'
ENDDATE = 'enddate'

MOBILE_NO_NOT_BELONGS_TO_CURRENT_USER= 'MOBILE_NO_NOT_BELONGS_TO_CURRENT_USER'
RECIPIENT_USER_NOT_FOUND = 'RECIPIENT_USER_NOT_FOUND '
RECIPIENT_USER_NOT_ACTIVE='RECIPIENT_USER_NOT_ACTIVE '
INSUFFICIENT_BALANCE='INSUFFICIENT_BALANCE '
NO_ACTIVE_WALLET = 'NO_ACTIVE_WALLET_ACCOUNT_FOUND'
MISMATCH_WALLET_CURRENCY_TRANSFER = 'MISMATCH_WALLET_CURRENCY_TRANSFER '
TRANSACTION_FAILED = "TRANSACTION_FAILED "
SENDER_RECIPIENT_MATCHED= "SENDER_RECIPIENT_MATCHED "
INVALID_AMOUNT_TRANSFER="INVALID_AMOUNT_TRANSFER "
WALLET_BALANCE_UPDATE_FAILED = 'WALLET_BALANCE_UPDATE_FAILED '











