# Generated by Django 2.2.12 on 2020-09-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletdetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='last_updated_time',
        ),
        migrations.RemoveField(
            model_name='wallethistory',
            name='last_updated_time',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='transaction_date',
        ),
    ]
